import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tigerent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        Tigerent
      </h1>
      <h2 className={styles.subtitle}>虎の威を借りるサブスク</h2>
      <div className={styles.ain}>
        <div className={styles.grid}>
          <a className={styles.button}>お申し込みはこちら</a>
        </div>
      </div>
    </div>
  )
}
